version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8000
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        depends_on:
            - db
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=test_project
            - DB_USERNAME=postgres
            - DB_PASSWORD=admin

    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=test_project
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
